export const DANGKY_REQUESTED = 'DANGKY_REQUESTED';
export const DANGKY_SUCCEED = 'DANGKY_SUCCEED';
export const DANGKY_FAILED = 'DANGKY_FAILED';

export const DANGNHAP_REQUESTED = 'DANGNHAP_REQUESTED';
export const DANGNHAP_SUCCEED = 'DANGNHAP_SUCCEED';
export const DANGNHAP_FAILED = 'DANGNHAP_FAILED';
export const DANGXUAT = 'DANGXUAT';
